version: "3.9"

services:
  web:
    build: ./web
    container_name: pcprep_web
    depends_on:
      db:
        condition: service_healthy
    environment:
      FLASK_ENV: production
      SECRET_KEY: ${SECRET_KEY:-change-me}
      DATABASE_URL: postgresql+psycopg2://pcprep:pcprep@db:5432/pcprep
      # 1 seul worker + eventlet (temps réel local sans MQ)
      GUNICORN_CMD_ARGS: "-w 1 -k eventlet -t 120 -b 0.0.0.0:8000"
    ports:
      - "7000:8000"
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: pcprep_db
    environment:
      POSTGRES_DB: pcprep
      POSTGRES_USER: pcprep
      POSTGRES_PASSWORD: pcprep
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pcprep -d pcprep || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
