version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: pcisere
      POSTGRES_USER: pcisere
      POSTGRES_PASSWORD: pcisere
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pcisere -d pcisere"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://pcisere:pcisere@db:5432/pcisere
      JWT_SECRET: supersecretjwt
      CORS_ORIGINS: http://localhost,http://127.0.0.1
      ADMIN_DEFAULT_PASSWORD: admin
      APP_PORT: "7000"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "7000:7000"

volumes:
  db_data:
