version: '3.9'

services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8000 wsgi:app
    volumes:
      - .:/app
    ports:
      - "7000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: poshaehoze
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 5s