version: "3.9"

services:
  web:
    build: .
    container_name: secouristes_web
    command: >
      bash -lc "gunicorn -k eventlet -w 1 wsgi:app --bind 0.0.0.0:8000"
    volumes:
      - .:/srv
    ports:
      - "7000:8000"
    depends_on:
      - db
      - redis
    environment:
      FLASK_ENV: production
      DATABASE_URL: postgresql://admin:admin@db:5432/secouristes
      REDIS_URL: redis://redis:6379/0

  db:
    image: postgres:15
    container_name: secouristes_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: secouristes
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: secouristes_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
